class colors {
  static white = '#fff';
  static red = '#FE0000';
  static black = '#000000';
  static gray = '#808080';
  static lightGray = '#BCBCBC';
  static button = '#5B5BFF';
  static card_bg = '#EFEFFF';
  static brand_primary = '#AC343D';
  static brand_secondary = '#FFF4F5';
  static screen_bg = ' #F5F5F5';
  static screen_bgDark = '#EBE8E2';
  static text_primary = '#454444';
  static text_secondary = '#777777';
  static error = '#E03232';
  static gray_font = '#969393';
  static account_font = '#565252';
  static textInput_color = '#FAFAFA';
  static orange_bg = '#FFE3B8';
  static awaiting_text = '#C77B0A';
  static text_orange = '#F6990C';
  static text_green = '#0AA853';
  static bg_green = '#B8FFDD';
  static text_pink = '#EE4FAF';
  static bg_pink = '#FFDCF7';
  static text_date = '#727272';
  static pending_text = '#F5B10C';
  static complete_text = '#3E9515';
  static text_input_color = '#E6E6E6';
  static text_boxes: any | ColorValue | undefined;
  static text_boxes: any | ColorValue | undefined;
  static bg_detailDiv: any;
}
export default colors;
